name: 'pr-update'
description: 'A basic GitHub Action to create and update PullRequests from a source to a target branch'
author: 'k3rnel-pan1c'
branding:
  icon: 'git-pull-request'
  color: 'green'
inputs:
  token:
    required: true
    description: 'The GitHub Token to use by this Action'
  pr_title:
    required: true
    description: 'The title of the PR that should be created/updated'
  pr_source:
    required: true
    description: 'The source branch name the PR should have'
  pr_target:
    required: false
    description: 'The target branch name the PR should have'
  pr_body:
    required: false
    description: 'The body of the PR to create'
  pr_body_append_pr_diffs:
    required: false
    description: 'When enabled adds titles and links from PRs that "pr_source" and "pr_target" differ'
  pr_labels:
    required: false
    description: 'A comma separated list of labels to add to the PR'
  pr_assignees:
    required: false
    description: 'A comma separated list of assignees to add to the PR'
outputs:
  pr_nr:
    description: 'The number of the created/updated PR'
runs:
  using: 'node16'
  main: 'dist/index.js'
