name: Sync Label Config

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 1 * *'

permissions:
  contents: read
  issues: write


jobs:
  sync-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: EndBug/label-sync@34787058c3498a674f22425940797579f4bd89f2 # v2.3.1
        with:
          source-repo: k3rnels-actions/.github
          token: ${{ secrets.GITHUB_TOKEN }}
