name: Sync Label Config

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 1 * *'

permissions:
  contents: read
  issues: write


jobs:
  sync-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: EndBug/label-sync@52074158190acb45f3077f9099fea818aa43f97a # v2.3.3
        with:
          source-repo: k3rnels-actions/.github
          token: ${{ secrets.GITHUB_TOKEN }}
