name: Sync Label Config

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 1 * *'

permissions:
  contents: read
  issues: write


jobs:
  sync-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: EndBug/label-sync@da00f2c11fdb78e4fae44adac2fdd713778ea3e8 # v2.3.2
        with:
          source-repo: k3rnels-actions/.github
          token: ${{ secrets.GITHUB_TOKEN }}
