name: Sync Label Config

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 1 * *'

jobs:
  sync-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: EndBug/label-sync@v2.3.0
        with:
          source-repo: k3rnels-actions/.github
          token: ${{ secrets.GITHUB_TOKEN }}
